# Generated by Django 4.2.3 on 2023-07-29 04:45

from django.db import migrations, models
import managements.models
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('image', models.ImageField(default=managements.models.get_default_img_filepath, max_length=255, upload_to=pages.models.get_question_img_filepath, verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('describe', models.CharField(max_length=255, verbose_name='Describe')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
