# Generated by Django 4.2.3 on 2023-07-29 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='answers_count',
            field=models.IntegerField(default=0, verbose_name='Answers count'),
        ),
        migrations.AddField(
            model_name='question',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Views count'),
        ),
        migrations.AddField(
            model_name='question',
            name='votes_count',
            field=models.IntegerField(default=0, verbose_name='Votes count'),
        ),
    ]
