# Generated by Django 4.2.3 on 2023-07-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_question_describe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='votes_count',
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('votes_count', models.IntegerField(default=0, verbose_name='Votes count')),
                ('answers_count', models.IntegerField(default=0, verbose_name='Answers count')),
                ('views_count', models.IntegerField(default=0, verbose_name='Views count')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='pages.question')),
            ],
            options={
                'verbose_name_plural': 'Counts',
            },
        ),
    ]
