# Generated by Django 4.2.3 on 2023-07-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_question_answers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='describe',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default='Default', max_length=7650, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
