# Generated by Django 4.2.3 on 2023-07-30 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_remove_question_describe_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='voted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='voted_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
