# Generated by Django 4.2.3 on 2023-07-30 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import managements.models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0007_alter_count_voted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('image', models.ImageField(default=managements.models.get_default_img_filepath, max_length=255, upload_to=pages.models.get_answer_img_filepath, verbose_name='Image')),
                ('description', models.CharField(max_length=7650, verbose_name='Description')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pages.question')),
            ],
            options={
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='AnswerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('votes_count', models.IntegerField(default=0, verbose_name='Votes count')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_counts', to='pages.question')),
                ('voted_by', models.ManyToManyField(blank=True, related_name='answer_voted_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Answer Counts',
            },
        ),
        migrations.CreateModel(
            name='QuestionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('votes_count', models.IntegerField(default=0, verbose_name='Votes count')),
                ('answers_count', models.IntegerField(default=0, verbose_name='Answers count')),
                ('views_count', models.IntegerField(default=0, verbose_name='Views count')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_counts', to='pages.question')),
                ('voted_by', models.ManyToManyField(blank=True, related_name='question_voted_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Question Counts',
            },
        ),
        migrations.DeleteModel(
            name='Count',
        ),
    ]
