# Generated by Django 4.2.3 on 2023-07-30 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_answer_account_alter_question_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercount',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_counts', to='pages.answer'),
        ),
    ]
