# Generated by Django 4.2.3 on 2023-07-31 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_answercount_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncount',
            name='answers_count',
        ),
    ]
