# Generated by Django 4.2.3 on 2023-07-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_questioncount_answers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Accepted'),
        ),
    ]
