# Generated by Django 4.2.3 on 2023-08-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_answercounts_questioncounts_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags'),
        ),
    ]
