# Generated by Django 4.2.3 on 2023-08-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_room_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
