# Generated by Django 4.2.3 on 2023-08-04 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0017_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='occupied',
            field=models.BooleanField(default=False, verbose_name='Occupied'),
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
