# Generated by Django 4.2.3 on 2023-08-04 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0018_room_expert_room_occupied_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
        migrations.AddField(
            model_name='room',
            name='bot',
            field=models.BooleanField(default=False, verbose_name='Bot'),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Problems',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='problem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_rooms', to='pages.problem'),
        ),
    ]
