# Generated by Django 4.2.3 on 2023-08-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_room_name_remove_room_slug_room_bot_problem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='occupied',
        ),
        migrations.AddField(
            model_name='room',
            name='assigned',
            field=models.BooleanField(default=False, verbose_name='Assigned'),
        ),
    ]
