# Generated by Django 4.2.3 on 2023-08-05 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_room_occupied_room_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='problem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='pages.problem'),
        ),
    ]
