# Generated by Django 4.1.10 on 2023-08-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_room_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bot',
        ),
        migrations.AddField(
            model_name='room',
            name='ai',
            field=models.BooleanField(default=False, verbose_name='AI'),
        ),
    ]
