# Generated by Django 4.1.7 on 2023-03-14 14:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('rme', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=64, unique=True)),
                ('pimg', models.ImageField(blank=True, default=accounts.models.get_default_pimg, max_length=255, null=True, upload_to=accounts.models.get_pimg_filepath)),
                ('fname', models.CharField(blank=True, max_length=32, null=True)),
                ('lname', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(blank=True, max_length=32, null=True)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('house_no', models.CharField(blank=True, max_length=128, null=True)),
                ('address_line', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('social_li', models.CharField(blank=True, max_length=255, null=True)),
                ('social_fb', models.CharField(blank=True, max_length=255, null=True)),
                ('social_tw', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
