# Generated by Django 4.0.10 on 2023-08-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid'),
        ),
    ]
