# Generated by Django 4.0.10 on 2023-08-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_token_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
