# Generated by Django 4.2.3 on 2023-07-18 04:58

from django.db import migrations, models
import django.db.models.deletion
import managements.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('image', models.ImageField(default=managements.models.get_default_img_filepath, max_length=255, upload_to=managements.models.get_category_img_filepath, verbose_name='Image')),
                ('name_bn', models.CharField(max_length=255, verbose_name='Name (bn)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (en)')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('bn_key_1', models.CharField(max_length=255, verbose_name='Name (bn)')),
                ('bn_value_1', models.CharField(max_length=7650, verbose_name='Details (bn)')),
                ('en_key_1', models.CharField(max_length=255, verbose_name='Name (en)')),
                ('en_value_1', models.CharField(max_length=7650, verbose_name='Details (en)')),
            ],
            options={
                'verbose_name_plural': 'Information',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('image', models.ImageField(default=managements.models.get_default_img_filepath, max_length=255, upload_to=managements.models.get_subcategory_img_filepath, verbose_name='Image')),
                ('name_bn', models.CharField(max_length=255, verbose_name='Name (bn)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (en)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='managements.category')),
                ('information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information', to='managements.information')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
    ]
