# Generated by Django 4.1.10 on 2023-08-18 09:11

from django.db import migrations, models
import django.db.models.deletion
import managements.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('image', models.ImageField(default=managements.models.get_default_img_filepath, max_length=255, upload_to=managements.models.get_category_img_filepath, verbose_name='Image')),
                ('name_bn', models.CharField(max_length=255, verbose_name='Name (bn)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (en)')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('image', models.ImageField(default=managements.models.get_default_img_filepath, max_length=255, upload_to=managements.models.get_subcategory_img_filepath, verbose_name='Image')),
                ('name_bn', models.CharField(max_length=255, verbose_name='Name (bn)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (en)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='managements.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('name_bn', models.CharField(max_length=255, verbose_name='Name (bn)')),
                ('details_bn', models.CharField(max_length=7650, verbose_name='Details (bn)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (en)')),
                ('details_en', models.CharField(max_length=7650, verbose_name='Details (en)')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='managements.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Information',
            },
        ),
        migrations.CreateModel(
            name='DiseaseProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('image', models.ImageField(default=managements.models.get_default_img_filepath, max_length=255, upload_to=managements.models.get_disease_img_filepath, verbose_name='Image')),
                ('name_bn', models.CharField(max_length=765, verbose_name='Name (bn)')),
                ('insects_causes_bn', models.CharField(blank=True, max_length=765, null=True, verbose_name='Insects/Causes (bn)')),
                ('solution_bn', models.CharField(blank=True, max_length=765, null=True, verbose_name='Solution (bn)')),
                ('warning_bn', models.CharField(blank=True, max_length=765, null=True, verbose_name='Warning (bn)')),
                ('name_en', models.CharField(max_length=765, verbose_name='Name (en)')),
                ('insects_causes_en', models.CharField(blank=True, max_length=765, null=True, verbose_name='Insects/Causes (en)')),
                ('solution_en', models.CharField(blank=True, max_length=765, null=True, verbose_name='Solution (en)')),
                ('warning_en', models.CharField(blank=True, max_length=765, null=True, verbose_name='Warning (en)')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_problem', to='managements.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Diseases/Problems',
            },
        ),
    ]
