# Generated by Django 4.2.3 on 2023-07-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='bn_value_1',
            new_name='bn_details',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='bn_key_1',
            new_name='bn_name',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='en_key_1',
            new_name='en_name',
        ),
        migrations.RemoveField(
            model_name='information',
            name='en_value_1',
        ),
        migrations.AddField(
            model_name='information',
            name='en_details',
            field=models.CharField(default='Default', max_length=7650, verbose_name='Details (en)'),
            preserve_default=False,
        ),
    ]
