# Generated by Django 4.2.3 on 2023-07-22 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_rename_bn_details_information_details_bn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='managements.subcategory'),
        ),
    ]
