# Generated by Django 4.2.3 on 2023-07-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0005_diseaseproblem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseaseproblem',
            options={'verbose_name_plural': 'Diseases/Problems'},
        ),
    ]
